---
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Rails/SkipsModelValidations:
  Exclude:
    - spec/factories/**/*.rb

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/integration/**/*.rb

RSpec/ScatteredSetup:
  Exclude:
    - spec/integration/**/*.rb

RSpec/VariableName:
  IgnoredPatterns:
    - ^Authorization$

Style/Documentation:
  Exclude:
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/application.rb
    - db/migrate/*.rb

Style/SymbolProc:
  Exclude:
    - spec/**/*.rb
