language: ruby
dist: bionic
cache: bundler
addons:
  postgresql: "11"
before_script:
  - bin/rails db:setup
env:
  global:
    secure: B8pdk07wtYcbVYcMPWN1VaWYqC9Gpn5IfKPho/Z10SrlX86lgdhWqYEgYBMWRvarqOSyjlUB0J/4AqCt6+5F4sP/mA73PoKIerJL0OEtmbKEBkUMqUZiNtV9vzpnbTGKF5akVKna2SpnlufAHCY1kM+QtlIrvEYyyA7j7FCZCn180WBROVc/78ZUU0jaGhg+IsDdVKLksr4ZgnvI7B8eEfOyp1esh1K1eZ0BCUSgeyXQiG43jLGD0eqPPgiCQ2kLlyYhnRt1q6C5Blq0QXBWa7Mfwwv5YE3UX8bOMaM5MkKguwP38vJK5bIPkk+yCZb2LTweX8lo6pGPhyBPU5egGPl3KCGeeoQ+z6kZOC+h8tnWOJTQOSv4qPeSxhOWCzUoHFZbSHG6qrxdBBfhbN6bKiu5KYJ8eTIicA5g2mQCaltUQjNxxx9dDEt3KP4FAfnTunG9CmjOwUaRpale8or5t1bKsjHxVtZdK+tz6CXIwHpBdS1Ek8TOCt3hwTKFGfhkHQlqTivt7Z0XArMiotDKsb3bqhbJGOwRh30Wk4aC93Flu4mM1zrGhCEFQAgwJ7BWEf/DXm5CZsN7hchZVks0zs1BuN75pJvmL9nwPZ2JG2wLKKhSwKknz3XzJ0Drm3u4TsiZoxxU0tIAnKkMKp+p5goLYo31yw3SoSH7z0ubDdc=
